### ISSUE TITLE
Update from react-native-cli 

### ISSUE THREAD

**Issue by kpiascik** [magic-script/magic-script-cli#121]
The last version of `react-native-cli` was published 3 years ago.  https://facebook.github.io/react-native/docs/getting-started recommends uninstalling `react-native-cli` from npm and using `npx` instead.  We should update to use `npx` for our `init` and `run` commands.

**Comment by panwrona** [comment]
Is is ready in https://github.com/magic-script/magic-script-cli/pull/128
