### ISSUE TITLE
Command: `magic-script build android` fails

### ISSUE THREAD

**Issue by grozdanov** [magic-script/magic-script-cli#134]
Running `magic-script build android` from the terminal for newly created project fails with the following error:
```
BUILD FAILED in 0s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/lab/Downloads/magic-script-cli/testapp/reactnative/android/settings.gradle'

* What went wrong:
Could not compile settings file '/Users/lab/Downloads/magic-script-cli/testapp/reactnative/android/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57
```
The following workaround steps resolve the issue:
1. Open the project from the Android Studio - that will trigger gradle sync
2. Build the project from the Android Studio
3. Run `magic-script build android` from the terminal again

**Comment by panwrona** [comment]
I need @nickilin to provide some more information because from what I remember we made it work last week, but the problem returned at some point

**Comment by Ninikitos** [comment]
Basically I pulled latest catalog app and tried to install it with latest cli 2.3.2. We make it work in the past with a workaround that you told me but right now with new cli published I would expect catalog app work out of the box with cli build for android

**Comment by Ninikitos** [comment]
@panwrona Thats what out put I see while build for android
`mlla4155:magic-script-components-catalog lab$ magic-script build android
npm install: installing
/usr/local/lib/node_modules/magic-script-cli/commands/build.js:22
      throw err;
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install' ]
}`

**Comment by panwrona** [comment]
@nickilin We updated `magic-script-components-catalog` to new structure, it would be nice if you could test again if it works on your machine:
1. Make sure you have the latest `magic-script-cli` installed
2. Clone `magic-script-components-catalog` or checkout to master and pull changes
3. Follow steps from documentation in `magic-script-cli` and check if it works

**Comment by Ninikitos** [comment]
@panwrona Thank you for a heads up. I will test later today and update you with my results

**Comment by Ninikitos** [comment]
I was able to verify on MacOS Catalina side. We can close this issue. Thank You @panwrona and @grozdanov
