### ISSUE TITLE
Install command does not support OUTNAME

### ISSUE THREAD

**Issue by grozdanov** [magic-script/magic-script-cli#151]
**Steps to Reproduce / Actual Behavior:**
1. Build MPK using OUTNAME command/parameter: `magic-script build`
Make sure the OUTNAME parameter (from app.package) has different name than `app.mpk`
2. Install the MPK: `magic-script install` 
error: `error: File not found: '.out/app/app.mpk'`

Example:
```
mlla1848:MxsTestRc10 jgrills$ magic-script build
Adding tail data
Tail data added successfully to 'digest.sha512.signed'built package: .out/custom/custom.mpk

mlla1848:MxsTestRc10 jgrills$ magic-script installmldb install .out/app/app.mpk
error: File not found: '.out/app/app.mpk'
```
**Expected Behavior:**
Magic-Script install should support OUTNAME command/parameter

**Comment by panwrona** [comment]
When you type `magic-script --help`, the install command has 2 arguments, target & path. With path you can specify the path to the *.mpk file, where `.out/app/app.mpk' is the default path.

Can you try with `magic-script install lumin .out/custom/custom.mpk` ?

**Comment by panwrona** [comment]
@grozdanov Do you have some feedback on this issue?

**Comment by grozdanov** [comment]
@panwrona the SCRIPT-742 has been closed.
