### ISSUE TITLE
Update typescript template

### ISSUE THREAD

**Issue by panwrona** [magic-script/magic-script-cli#153]
- The rollup config for typescript multiplatform must match the one from js multiplatform
- In multiplatform structure, the tsconfig.json and types have to be in the top-level directory

**Comment by panwrona** [comment]
@kpiascik @tonycuadra please check this repository and give me feedback if the typescript config is good enough for our purposes: https://github.com/panwrona/TypescriptTest

**Comment by tonycuadra** [comment]
It works well for me. I confirmed that react and magic script component type declarations are correctly resolved. I also installed a react router dependency at top level and confirmed that those type declarations also worked in vs code.
