### ISSUE TITLE
Check for valid app name and app IDs in init command.

### ISSUE THREAD

**Issue by creationix** [magic-script/magic-script-cli#169]
Currently the input for the app name `com.foo.bar...` is a free-form field and lets developers put in names that will be rejected later on as a strange "manifest failure".  We should check using a regular expression to catch this early on.

**Comment by creationix** [comment]
It looks like we have some check already.  Maybe it just needs to be updated to match exactly what the platform is expecting.

**Comment by panwrona** [comment]
@creationix I've researched some time ago the limitations for package ID on android & ios and current for Lumin and packed them into one regex. 

The example test is here: https://regex101.com/r/Rk4fco/1 . 

Please confirm if everything works well, or we have to change some checks to match Lumin requirements
