### ISSUE TITLE
magic-script --help should discuss build types

### ISSUE THREAD

**Issue by jgrills-ml** [magic-script/magic-script-cli#170]
It should indicate the default build is a debug build. It should also document the command line to do a release build instead.

**Comment by jgrills-ml** [comment]
It should also list valid [target] choices
It should also call out `build -h` for host builds

**Comment by jgrills-ml** [comment]
`run --debug=false` also should get called out

**Comment by panwrona** [comment]
I added message to CLI help menu. When you type `magic-script --help` you'll see '! Usage: Type magic-script <command> --help for detailed help !` which means you have to specify command name to get detailed help. I think it is a limitation from yargs library we use for CLI
