### ISSUE TITLE
Rollup needs to be installed globally

### ISSUE THREAD

**Issue by brianpeiris** [magic-script/magic-script-cli#53]
The getting started instructions don't mention that rollup needs to be installed globally. `magic-script build -i` after `magic-script init` fails otherwise.
Alternately, you could change the init'd `build` script to run `npx rollup -c` instead of just `rollup -c`.

**Comment by kpiascik** [comment]
Thanks @brianpeiris. I'll look at this.

**Comment by creationix** [comment]
It shouldn't fail if you run `npm install` first since we include `rollup` ad ` dev dependency and run it using `npm run`

**Comment by grozdanov** [comment]
The build command will run `npm install` upfront if the required packages haven't been installed.
